// <auto-generated />
using System;
using Greenhouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Greenhouse.Migrations
{
    [DbContext(typeof(GreenhouseContext))]
    [Migration("20250823001704_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Greenhouse.Models.Plants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("SensorValue")
                        .HasColumnType("real");

                    b.Property<DateTime>("Sensor_Event")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Plant", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
