// <auto-generated />
using System;
using Greenhouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Greenhouse.Migrations
{
    [DbContext(typeof(GreenhouseContext))]
    partial class GreenhouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Greenhouse.Models.Plants", b =>
                {
                    b.Property<string>("PlantName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("SensorValue")
                        .HasColumnType("real");

                    b.Property<DateTime>("Sensor_Event")
                        .HasColumnType("datetime2");

                    b.HasKey("PlantName");

                    b.ToTable("Plant", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
